### ISSUE TITLE
Turning on HalfRes on a Samsung A32 turns a part of the scene black/dark

### ISSUE THREAD

**Issue by woondossier** [N8python/n8ao#9] opened 2023-06-07 14:22 UTC
The issue happens on both Chrome 112 and the Samsung browser in both the Example and our own software.
All other mobile devices are working fine, including both Android and iOS devices.

I've added a screenshot of what's happening.
![image](https://github.com/N8python/n8ao/assets/56030084/100f30ed-2012-4ff1-b17c-3abb38b43711)

**Comment by N8python** [comment] 2023-06-07 21:54
I'm not sure what could be causing this. Do things work smoothly without half-res?

**Comment by woondossier** [comment] 2023-06-08 12:09
Yes it's something in the down/upscaling that causes this it seems, we've tried toggling dept aware on/off and that didnt change anything. As soon as half res is turned off it works fine. 

We've tested it on other mobiles devices we have here in the office/our personal devices: 1+ 9 Pro and 6T, iPhone X, two old iPad pros and a Samsung galaxy tab S7 and a Pocophone F1.

**Comment by N8python** [comment] 2023-06-08 13:59
Perhaps it has to do with the use of MRT - does the Samsung A32 support that?

**Comment by N8python** [comment] 2023-06-09 20:26
In this case, I'm really not sure what could be going wrong - sorry!

**Comment by fanjules** [comment] 2023-06-14 11:09
I had a similar problem, I posted about it here but I think the issue had been closed at the time so I think you must not have seen it.

https://github.com/N8python/n8ao/issues/7

This was on Moto G4, Moto G5, Moto G8 where I would get vertical banding and the SSAO would be in the wrong place on the screen.  A problem would also happen on iPad Air (iOS 15x) where I get a black screen (both in Safari and Chrome).

**Comment by N8python** [comment] 2023-06-15 19:30
Oh. Oh. OH MY GOD IM AN IDIOT.

I forgot to specify a highp sampler. Let me see if that fixes it.

**Comment by N8python** [comment] 2023-06-15 19:32
Does it work now?

**Comment by fanjules** [comment] 2023-06-15 21:58
It worked perfectly for me on my Android devices, and the performance is amazing!

iOS is still a black screen, but this is an older device stuck on iOS15 so I shouldn't lose sleep over it.  Maybe halfRes uses an unsupported GPU function here.

**Comment by N8python** [comment] 2023-06-15 22:09
Yes - try the MRT threejs example mentioned earlier... if that doesn't work, the issue isn't N8AO-centric.

**Comment by ButzYung** [comment] 2023-06-17 18:46
I suspect some recent changes have screwed up the halfRes mode again. In your official example, if I turn on halfRes, the AO looks as if it's inverted.

![_](https://github.com/N8python/n8ao/assets/3256084/6a7d9555-7bd5-414b-931a-d3be81a3f222)

In my own app which uses vanilla three.js without `postprocessing`, the behavior is a bit different. The AO map looks weird if only I start rotating the camera up.

![_02](https://github.com/N8python/n8ao/assets/3256084/ebf2f925-65de-4dc9-947f-923040272366)

**Comment by N8python** [comment] 2023-06-18 20:56
WEIRD - looking into it immediately.

**Comment by N8python** [comment] 2023-06-18 21:14
Should be fixed in the latest version - 1.6.6.

**Comment by ButzYung** [comment] 2023-06-20 11:34
The fix works. Thanks.

**Comment by N8python** [comment] 2023-06-20 12:12
Glad to hear it!

**Closed** 2023-06-23 18:06 UTC

**Comment by verekia** [comment] 2024-10-15 02:23
I am having a similar problem with my Android Pixel 8. The scene turns black when `halfRes` is enabled. No problem on desktop. With 1.9.2.
